name: $(date:yyMM).$(Build.BuildId).$(date:dd).$(date:HHmm)

trigger:
- master

resources:
- repo: self

variables:
  projects: '**/*.csproj'
  buildConfiguration: 'Release'
  pluginName: 'Soneta.KadryPlace.Reports'   # <-- nazwa Twojego projektu
  versionNumber: '$(date:yyMM).$(Build.BuildId).$(date:dd).$(date:HHmm)'
  artifactName: 'drop'
  isNotPR: $[ne(variables['Build.Reason'], 'PullRequest')]

stages:
- stage: Build_Test
  displayName: Build and test
  jobs:
  - job: Build
    displayName: Build
    timeoutInMinutes: 300
    pool:
      name: Default

    steps:
    - checkout: self
      clean: true

    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '$(projects)'

    - task: DotNetCoreCLI@2
      displayName: Build
      condition: and(succeeded(), eq(variables.isNotPR, true))
      inputs:
        command: build
        projects: '$(projects)'
        arguments: >
          --configuration $(buildConfiguration)
          --no-restore
          /p:Version=$(versionNumber)
          /p:AssemblyVersion=$(versionNumber)
          /p:FileVersion=$(versionNumber)
          /p:InformationalVersion=$(versionNumber)
          /p:Product=$(Build.DefinitionName)
          /p:Company="Agemit Sp. z o.o."
          /p:Copyright="Copyright © $(date:yyyy) Agemit Sp. z o.o."

    - task: PublishSymbols@2
      displayName: Publish symbols
      condition: and(succeeded(), eq(variables.isNotPR, true))
      inputs:
        SearchPattern: '**\bin\$(buildConfiguration)\**\*.pdb'
        PublishSymbols: false
      continueOnError: true

    - task: CopyFiles@2
      displayName: Copy plugin DLL to staging
      condition: and(succeeded(), eq(variables.isNotPR, true))
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **\bin\$(buildConfiguration)\**\$(pluginName).dll
          **\bin\$(buildConfiguration)\**\$(pluginName).pdb
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true

    - publish: $(Build.ArtifactStagingDirectory)
      displayName: Publish artifacts
      condition: and(succeeded(), eq(variables.isNotPR, true))
      artifact: $(artifactName)