name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
- master

resources:
- repo: self

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  packageVersion: '1.0.$(Build.BuildId)'
  assemblyVersion: '1.0.0.0'
  fileVersion: '1.0.$(Build.BuildId).0'

stages:
- stage: Build_Test
  displayName: Build and test
  jobs:
  - job: Build_Test
    displayName: Build and test
    timeoutInMinutes: 300

    pool:
      name: Default

    steps:
    - checkout: self
      clean: true

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '$(solution)'
        arguments: >
          --configuration $(buildConfiguration)
          --no-restore
          /p:Version=$(packageVersion)
          /p:AssemblyVersion=$(assemblyVersion)
          /p:FileVersion=$(fileVersion)
          /p:InformationalVersion=$(Build.BuildNumber)

    - powershell: |
        if (Get-ChildItem -Recurse -Filter *.UnitTest.csproj -File) {
          Write-Host "##vso[task.setVariable variable=RunUnitTests]True"
        }
        else {
          Write-Host "##vso[task.setVariable variable=RunUnitTests]False"
        }
      displayName: Discover unit tests

    - task: DotNetCoreCLI@2
      condition: and(succeeded(), eq(variables['RunUnitTests'], 'True'))
      displayName: Run unit tests
      inputs:
        command: test
        projects: '**/*.UnitTest.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**\bin\$(buildConfiguration)\**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      condition: succeededOrFailed()

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
      condition: succeededOrFailed()